### ISSUE TITLE
README.md and CONTRIBUTING.md have syntax errors.

### ISSUE THREAD

**Issue by RobRoseKnows** [googlesamples/android-ScreenCapture#11]
Two of the URLs in README.md are not encoded properly and the URLs in CONTRIBUTING.md have syntax errors.

Submitting an issue because CONTRIBUTING.md says to, but I've already fixed it and will post a PR shortly.

**Comment by RobRoseKnows** [comment]
Just submitted a fix in PR #12.

**Comment by thagikura** [comment]
Thanks. It's merged now.
