### ISSUE TITLE
App completely crashes phone and tablet when ran twice

### ISSUE THREAD

**Issue by lfdversluis** [googlesamples/android-ScreenCapture#2]
I imported the project into android studio, ran the app.

When you press start it works fine, then I press stop and it stops. Now when I press play again, the device crashes fully. It no longer responds to touch, soft keys and hardware buttons (turn off screen etc. no longer works). The only option is to press and hold the power button to force the device into rebooting.

No logs could be captured because the device fully crashes, so I assume a memory leak or something

Tested on both a Nexus 7 and Samsung Galaxy S4, both updated to the latest version of android 5 as of typing

**Comment by thagikura** [comment]
The issue was not reproducible. Verified with an emulator with API level 22 and 28.
Please reopen if it still persists.
