### ISSUE TITLE
Doesn't do anything...

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlesamples/android-ScreenCapture#4]
i tried the sample. Pressed "start" and nothing happens. Also tried "stop" after that, and still nothing. What is going on?
I have given it permission to capture the screen, btw.

**Comment by AndroidDeveloperLB** [comment]
also i got it to crash on some case, when pressing home and then returning to the app (it's more steps than this, but i can't reproduce) . Here's the log:

01-01 19:13:27.876 7249-7302/com.example.android.screencapture E/Surface: dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -22
01-01 19:13:27.876 7249-7302/com.example.android.screencapture E/libEGL: eglMakeCurrent:895 error 3003 (EGL_BAD_ALLOC)
01-01 19:13:27.876 7249-7302/com.example.android.screencapture A/OpenGLRenderer: Failed to make current on surface 0xb486d220, error=EGL_BAD_ALLOC
01-01 19:13:27.876 7249-7302/com.example.android.screencapture A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 7302 (RenderThread)
01-01 19:14:18.221 9294-9344/com.example.android.screencapture E/Parcel: dup failed in Parcel::read, fd 1 of 4
                                                                           dup(-2147483647) = -1 [errno: 9 (Bad file number)]
                                                                           fcntl(-2147483647, F_GETFD) = -1 [errno: 9 (Bad file number)]
                                                                           flat 0x0 type 0

**Comment by thagikura** [comment]
I think it's fixed now? It's working for me. Let me close this for now. Please reopen if it still persists.

**Comment by AndroidDeveloperLB** [comment]
Seems so, but can you also show how to do more things with it? Like save into a video file? And with audio?
