### ISSUE TITLE
Media Projection API Sample showing “Unfortunately , System UI has stopped” in Lenovo Tab3 7 Essential API 22

### ISSUE THREAD

**Issue by Piashsarker** [googlesamples/android-ScreenCapture#8]
I am using google sample Media Projection code to capture screen share. **It's working fine on Pixel_XL AVD** but **Media Projection API Sample showing "Unfortunately , System UI has stopped" in Lenovo Tab3 7 Essentia API 22**, others apps running fine .

Here is a screenshot -![screenshot_2017-04-22-12-54-22](https://cloud.githubusercontent.com/assets/8473499/25302539/2da4d2e8-2762-11e7-9349-b498d5f43733.png)

**Comment by niralnaik** [comment]
as per lower build target it may not work i am no longer maintaining this
:) better to go to original googlecode.

**Comment by sukirti1** [comment]
Did you find a method to resolve this issue?

**Comment by thagikura** [comment]
The app worked for me with a Galaxy Nexus Emulator API level 22. 
Could you reopen the issue if it still persists?
